/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as GpaRouteImport } from './routes/gpa'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SubjectsSubjectIdQuizzesIndexRouteImport } from './routes/subjects.$subjectId.quizzes.index'
import { Route as SubjectsSubjectIdQuizzesQuizIdRouteImport } from './routes/subjects.$subjectId.quizzes.$quizId'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const GpaRoute = GpaRouteImport.update({
  id: '/gpa',
  path: '/gpa',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/$subjectId',
  path: '/$subjectId',
  getParentRoute: () => SubjectsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const SubjectsSubjectIdQuizzesIndexRoute =
  SubjectsSubjectIdQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => SubjectsSubjectIdRoute,
  } as any)
const SubjectsSubjectIdQuizzesQuizIdRoute =
  SubjectsSubjectIdQuizzesQuizIdRouteImport.update({
    id: '/quizzes/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => SubjectsSubjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/gpa': typeof GpaRoute
  '/notes': typeof NotesRoute
  '/pending': typeof PendingRoute
  '/quizzes': typeof QuizzesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/quizzes/$quizId': typeof SubjectsSubjectIdQuizzesQuizIdRoute
  '/subjects/$subjectId/quizzes/': typeof SubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/gpa': typeof GpaRoute
  '/notes': typeof NotesRoute
  '/pending': typeof PendingRoute
  '/quizzes': typeof QuizzesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/quizzes/$quizId': typeof SubjectsSubjectIdQuizzesQuizIdRoute
  '/subjects/$subjectId/quizzes': typeof SubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/announcements': typeof AnnouncementsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dashboard': typeof DashboardRoute
  '/gpa': typeof GpaRoute
  '/notes': typeof NotesRoute
  '/pending': typeof PendingRoute
  '/quizzes': typeof QuizzesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/quizzes/$quizId': typeof SubjectsSubjectIdQuizzesQuizIdRoute
  '/subjects/$subjectId/quizzes/': typeof SubjectsSubjectIdQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/announcements'
    | '/assistant'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/gpa'
    | '/notes'
    | '/pending'
    | '/quizzes'
    | '/subjects'
    | '/auth/callback'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/quizzes/$quizId'
    | '/subjects/$subjectId/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/announcements'
    | '/assistant'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/gpa'
    | '/notes'
    | '/pending'
    | '/quizzes'
    | '/subjects'
    | '/auth/callback'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/quizzes/$quizId'
    | '/subjects/$subjectId/quizzes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/announcements'
    | '/assistant'
    | '/auth'
    | '/complete-profile'
    | '/dashboard'
    | '/gpa'
    | '/notes'
    | '/pending'
    | '/quizzes'
    | '/subjects'
    | '/auth/callback'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/quizzes/$quizId'
    | '/subjects/$subjectId/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  DashboardRoute: typeof DashboardRoute
  GpaRoute: typeof GpaRoute
  NotesRoute: typeof NotesRoute
  PendingRoute: typeof PendingRoute
  QuizzesRoute: typeof QuizzesRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gpa': {
      id: '/gpa'
      path: '/gpa'
      fullPath: '/gpa'
      preLoaderRoute: typeof GpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/subjects/$subjectId/quizzes/': {
      id: '/subjects/$subjectId/quizzes/'
      path: '/quizzes'
      fullPath: '/subjects/$subjectId/quizzes/'
      preLoaderRoute: typeof SubjectsSubjectIdQuizzesIndexRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/quizzes/$quizId': {
      id: '/subjects/$subjectId/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/subjects/$subjectId/quizzes/$quizId'
      preLoaderRoute: typeof SubjectsSubjectIdQuizzesQuizIdRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SubjectsSubjectIdRouteChildren {
  SubjectsSubjectIdQuizzesQuizIdRoute: typeof SubjectsSubjectIdQuizzesQuizIdRoute
  SubjectsSubjectIdQuizzesIndexRoute: typeof SubjectsSubjectIdQuizzesIndexRoute
}

const SubjectsSubjectIdRouteChildren: SubjectsSubjectIdRouteChildren = {
  SubjectsSubjectIdQuizzesQuizIdRoute: SubjectsSubjectIdQuizzesQuizIdRoute,
  SubjectsSubjectIdQuizzesIndexRoute: SubjectsSubjectIdQuizzesIndexRoute,
}

const SubjectsSubjectIdRouteWithChildren =
  SubjectsSubjectIdRoute._addFileChildren(SubjectsSubjectIdRouteChildren)

interface SubjectsRouteChildren {
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRouteWithChildren
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSubjectIdRoute: SubjectsSubjectIdRouteWithChildren,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  DashboardRoute: DashboardRoute,
  GpaRoute: GpaRoute,
  NotesRoute: NotesRoute,
  PendingRoute: PendingRoute,
  QuizzesRoute: QuizzesRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
